// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1CtiC3lpKgyITRvQUMMeZoMfcfnKCPuw',
    appId: '1:33782550632:web:dee9204b39b54821952bdd',
    messagingSenderId: '33782550632',
    projectId: 'flutter-firebase-auth-bacd7',
    authDomain: 'flutter-firebase-auth-bacd7.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-bacd7.appspot.com',
    measurementId: 'G-MTL27X4CN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8kJ1hiCdbBajaOVB7qFcmrviYQwHLNo',
    appId: '1:33782550632:android:ce6419b5d516cd37952bdd',
    messagingSenderId: '33782550632',
    projectId: 'flutter-firebase-auth-bacd7',
    storageBucket: 'flutter-firebase-auth-bacd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5VBvESBhchKe9GfBeUBbM4P_RRnrJSs',
    appId: '1:33782550632:ios:256fbfd3536ebeb3952bdd',
    messagingSenderId: '33782550632',
    projectId: 'flutter-firebase-auth-bacd7',
    storageBucket: 'flutter-firebase-auth-bacd7.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5VBvESBhchKe9GfBeUBbM4P_RRnrJSs',
    appId: '1:33782550632:ios:83c87d290dce18a4952bdd',
    messagingSenderId: '33782550632',
    projectId: 'flutter-firebase-auth-bacd7',
    storageBucket: 'flutter-firebase-auth-bacd7.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
